import React, { Fragment } from 'react';
import { Link } from 'react-router-dom';
import { AppLayout } from '../components/AppLayout';
import { ArrowLeftIcon, SparklesIcon } from 'lucide-react';
type Section = {
  id: string;
  heading: string;
  paragraphs?: string[];
  list?: string[];
  trailingParagraphs?: string[];
};
type Part = {
  id: string;
  label: string;
  title: string;
  sections: Section[];
};
const parts: Part[] = [
{
  id: 'part-1',
  label: 'Part I',
  title: 'External AI-Generated Content',
  sections: [
  {
    id: 'overview',
    heading: '2. Overview',
    paragraphs: [
    'External AI-generated content refers to content created outside of Podify and imported into Podify projects.',
    'Examples include content created using:'],

    list: [
    'Suno',
    'Udio',
    'ElevenLabs',
    'ChatGPT',
    'Gemini',
    'Claude',
    'Midjourney',
    'Leonardo AI',
    'Runway',
    'Stable Diffusion',
    'Other third-party AI services']

  },
  {
    id: 'supported-content-types',
    heading: '3. Supported External Content Types',
    paragraphs: ['Users may import:'],
    list: [
    'AI-generated music',
    'AI-generated sound effects',
    'AI-generated voice recordings',
    'AI-generated narration',
    'AI-generated scripts',
    'AI-generated research documents',
    'AI-generated artwork',
    'AI-generated images',
    'AI-generated videos',
    'AI-generated metadata'],

    trailingParagraphs: [
    'All imported content remains the responsibility of the user.']

  },
  {
    id: 'ownership-and-rights',
    heading: '4. Ownership and Rights Requirements',
    paragraphs: [
    'Before importing externally generated AI content, users must verify that they possess the rights necessary to use that content.',
    'Examples include:'],

    list: [
    'Commercial usage rights',
    'Distribution rights',
    'Publishing rights',
    'Reproduction rights',
    'Modification rights',
    'Monetization rights'],

    trailingParagraphs: [
    'Users are responsible for reviewing the terms and licensing requirements of the platform that generated the content.']

  },
  {
    id: 'external-music',
    heading: '5. Music Generated by External AI Systems',
    paragraphs: [
    'Users may import AI-generated music only if they possess the rights necessary to use the music.',
    'Before importing music, users should verify:'],

    list: [
    'Ownership status',
    'Commercial rights',
    'Monetization rights',
    'Distribution rights',
    'Attribution requirements',
    'Licensing restrictions'],

    trailingParagraphs: ['Podify does not verify ownership rights.']
  },
  {
    id: 'external-sfx',
    heading: '6. Sound Effects Generated by External AI Systems',
    paragraphs: [
    'Users may import AI-generated sound effects only if they possess the rights necessary to use those sound effects.',
    'Users are responsible for ensuring compliance with the terms of the generating platform.']

  },
  {
    id: 'external-scripts',
    heading: '7. Scripts Generated by External AI Systems',
    paragraphs: [
    'Users may import AI-generated scripts from third-party systems.',
    'Users remain responsible for:'],

    list: [
    'Fact-checking',
    'Accuracy verification',
    'Copyright compliance',
    'Legal compliance',
    'Final editorial review'],

    trailingParagraphs: ['Podify does not verify factual accuracy.']
  },
  {
    id: 'voice-cloning',
    heading: '8. AI-Generated Voices and Voice Cloning',
    paragraphs: [
    'Users may import AI-generated voices or voice clones only when they possess all required permissions and rights.',
    'Users are responsible for complying with:'],

    list: [
    'Consent requirements',
    'Publicity rights',
    'Privacy rights',
    'Contractual obligations',
    'Applicable laws'],

    trailingParagraphs: [
    'Unauthorized voice cloning may violate applicable laws.']

  },
  {
    id: 'copyright-compliance',
    heading: '9. Copyright and Licensing Compliance',
    paragraphs: [
    'Users remain solely responsible for ensuring imported AI-generated content complies with:'],

    list: [
    'Copyright laws',
    'Trademark laws',
    'Publicity rights',
    'Privacy rights',
    'Licensing agreements',
    'Terms of service of the generating platform'],

    trailingParagraphs: ['Podify does not determine ownership status.']
  },
  {
    id: 'consequences',
    heading: '10. Consequences of Unauthorized Use',
    paragraphs: [
    'If users import content they do not have the legal right to use, consequences may include:'],

    list: [
    'Copyright complaints',
    'DMCA takedown notices',
    'Removal from podcast platforms',
    'Removal from distribution services',
    'Account restrictions imposed by third-party platforms',
    'Loss of monetization',
    'Legal claims by rights holders',
    'Financial damages',
    'Civil penalties'],

    trailingParagraphs: [
    'Users remain solely responsible for such consequences.']

  },
  {
    id: 'third-party-terms',
    heading: '11. Third-Party Terms Govern Ownership',
    paragraphs: [
    'Ownership and licensing of externally generated AI content are governed by the terms of the platform that created the content.',
    'Podify does not alter, replace, override, or modify those ownership rights.']

  }]

},
{
  id: 'part-2',
  label: 'Part II',
  title: 'Internal AI-Assisted Content',
  sections: [
  {
    id: 'internal-overview',
    heading: '12. Overview',
    paragraphs: [
    'Podify may provide AI-assisted features that help users during the production process.',
    'These tools are intended to assist creators and streamline workflows.',
    'Internal AI tools are designed as production assistants, not autonomous creators.']

  },
  {
    id: 'internal-features',
    heading: '13. Internal AI Features',
    paragraphs: ['Internal AI features may assist with:'],
    list: [
    'Episode planning',
    'Research organization',
    'Script drafting',
    'Show notes generation',
    'Metadata suggestions',
    'Workflow recommendations',
    'Production assistance',
    'Editing recommendations',
    'Project organization'],

    trailingParagraphs: [
    'The final creative decisions remain with the user.']

  },
  {
    id: 'research-assistance',
    heading: '14. Research Assistance',
    paragraphs: [
    'Podify AI may assist users in organizing information provided by the user.',
    'Users may choose to:'],

    list: [
    'Enter information manually',
    'Provide notes',
    'Provide documents',
    'Provide approved research sources',
    'Provide approved links for review'],

    trailingParagraphs: [
    'Users remain responsible for verifying information before publication.']

  },
  {
    id: 'script-drafting',
    heading: '15. Script Drafting Assistance',
    paragraphs: [
    'Podify AI may help generate draft scripts using information supplied by the user.',
    'Users remain responsible for:'],

    list: [
    'Accuracy',
    'Editorial review',
    'Fact-checking',
    'Compliance with applicable laws',
    'Final approval'],

    trailingParagraphs: ['The AI acts only as a drafting assistant.']
  },
  {
    id: 'ai-recommendations',
    heading: '16. AI Recommendations',
    paragraphs: ['Podify AI may provide recommendations regarding:'],
    list: [
    'Episode structure',
    'Segment organization',
    'Workflow improvements',
    'Editing suggestions',
    'Production guidance'],

    trailingParagraphs: [
    'Recommendations are suggestions only. Users make all final decisions.']

  },
  {
    id: 'accuracy-disclaimer',
    heading: '17. AI Accuracy Disclaimer',
    paragraphs: [
    'AI systems can make mistakes.',
    'AI-generated content may contain:'],

    list: [
    'Errors',
    'Inaccuracies',
    'Outdated information',
    'Misinterpretations',
    'Fabricated information'],

    trailingParagraphs: [
    'Users should independently verify important information.']

  },
  {
    id: 'user-responsibility',
    heading: '18. User Responsibility',
    paragraphs: ['Users remain solely responsible for:'],
    list: [
    'Content accuracy',
    'Editorial decisions',
    'Publishing decisions',
    'Distribution decisions',
    'Legal compliance',
    'Copyright compliance'],

    trailingParagraphs: [
    'Use of AI does not transfer responsibility to Podify.']

  },
  {
    id: 'prohibited-uses',
    heading: '19. Prohibited Uses of AI',
    paragraphs: ['Users may not use AI features to:'],
    list: [
    'Promote violence',
    'Promote terrorism',
    'Promote unlawful activity',
    'Commit fraud',
    'Harass others',
    'Violate intellectual property rights',
    'Circumvent platform policies'],

    trailingParagraphs: [
    'All AI-assisted content remains subject to Podify policies.']

  },
  {
    id: 'platform-enforcement',
    heading: '20. Platform Enforcement',
    paragraphs: [
    'Podify reserves the right to investigate alleged violations involving AI-generated content.',
    'Podify may:'],

    list: [
    'Restrict access to content',
    'Restrict AI features',
    'Suspend accounts',
    'Terminate accounts'],

    trailingParagraphs: [
    'when necessary to enforce platform policies or comply with legal obligations.']

  },
  {
    id: 'summary',
    heading: '21. Summary',
    paragraphs: [
    'Podify supports both external AI-generated content and internal AI-assisted production tools.',
    'External AI content may be imported only when users possess the necessary rights and permissions.',
    'Internal AI tools are intended to assist users with planning, research organization, script drafting, and production workflows.',
    'In all cases, responsibility for content remains with the user. Users are responsible for:'],

    list: [
    'Ownership verification',
    'Licensing compliance',
    'Copyright compliance',
    'Content accuracy',
    'Publishing decisions',
    'Distribution decisions'],

    trailingParagraphs: [
    'AI can assist the production process, but responsibility for the final content always remains with the creator.']

  }]

}];

function SectionBlock({ section }: {section: Section;}) {
  return (
    <section id={section.id} className="scroll-mt-8">
      <h2 className="text-xl font-bold text-gray-900 mb-4">
        {section.heading}
      </h2>
      <div className="space-y-4">
        {section.paragraphs?.map((p, i) =>
        <p
          key={`p-${i}`}
          className="text-[15px] text-gray-700 leading-relaxed">
          
            {p}
          </p>
        )}
        {section.list &&
        <ul className="space-y-1.5 pl-1">
            {section.list.map((item) =>
          <li
            key={item}
            className="text-[15px] text-gray-700 leading-relaxed flex gap-3">
            
                <span className="text-violet-400 mt-1.5 flex-shrink-0">•</span>
                <span>{item}</span>
              </li>
          )}
          </ul>
        }
        {section.trailingParagraphs?.map((p, i) =>
        <p
          key={`t-${i}`}
          className="text-[15px] text-gray-700 leading-relaxed">
          
            {p}
          </p>
        )}
      </div>
    </section>);

}
export function LegalAi() {
  const allSections = parts.flatMap((part) => part.sections);
  return (
    <AppLayout>
      {/* Breadcrumb */}
      <div className="mb-6 flex items-center gap-2 text-sm text-gray-500">
        <Link
          to="/legal"
          className="inline-flex items-center gap-1 hover:text-violet-700 font-medium">
          
          <ArrowLeftIcon className="w-3.5 h-3.5" />
          Legal & Policies
        </Link>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-[1fr_260px] gap-12 max-w-6xl">
        <article>
          {/* Header */}
          <div className="mb-10">
            <div className="inline-flex items-center gap-1.5 bg-violet-50 text-violet-700 text-xs font-semibold px-2.5 py-1 rounded-md mb-4">
              <SparklesIcon className="w-3.5 h-3.5" />
              AI-Generated Content Policy
            </div>
            <h1 className="text-4xl font-bold text-gray-900 mb-3 tracking-tight">
              Podify AI-Generated Content Policy
            </h1>
            <p className="text-sm text-gray-500">
              Effective Date: [Insert Date]
            </p>
          </div>

          {/* Purpose */}
          <section id="purpose" className="mb-12 scroll-mt-8">
            <h2 className="text-xl font-bold text-gray-900 mb-4">1. Purpose</h2>
            <div className="space-y-4">
              <p className="text-[15px] text-gray-700 leading-relaxed">
                Podify supports the responsible use of artificial intelligence
                during the podcast production process.
              </p>
              <p className="text-[15px] text-gray-700 leading-relaxed">
                This policy explains the rules, responsibilities, ownership
                considerations, and usage requirements associated with both:
              </p>
              <ul className="space-y-1.5 pl-1">
                <li className="text-[15px] text-gray-700 leading-relaxed flex gap-3">
                  <span className="text-violet-400 mt-1.5 flex-shrink-0">
                    •
                  </span>
                  <span>
                    External AI-generated content imported into Podify
                  </span>
                </li>
                <li className="text-[15px] text-gray-700 leading-relaxed flex gap-3">
                  <span className="text-violet-400 mt-1.5 flex-shrink-0">
                    •
                  </span>
                  <span>
                    Internal AI-assisted content created through Podify features
                  </span>
                </li>
              </ul>
              <p className="text-[15px] text-gray-700 leading-relaxed">
                Users remain responsible for all content used within their
                projects regardless of whether the content was created by a
                human, an AI system, or a combination of both.
              </p>
            </div>
          </section>

          {/* Parts */}
          {parts.map((part, idx) =>
          <div key={part.id} id={part.id} className="mb-12 scroll-mt-8">
              <div className={idx === 0 ? 'mb-8' : 'mt-4 mb-8'}>
                <p className="text-xs font-bold text-violet-600 uppercase tracking-wider mb-1">
                  {part.label}
                </p>
                <h2 className="text-2xl font-bold text-gray-900 border-b border-gray-200 pb-3">
                  {part.title}
                </h2>
              </div>
              <div className="space-y-10">
                {part.sections.map((section) =>
              <SectionBlock key={section.id} section={section} />
              )}
              </div>
            </div>
          )}

          {/* Footer note */}
          <div className="mt-12 pt-8 border-t border-gray-100">
            <p className="text-xs text-gray-500 leading-relaxed">
              This AI-Generated Content Policy was last updated on the effective
              date shown above. Continued use of Podify after any update
              constitutes acceptance of the revised policy.
            </p>
          </div>
        </article>

        {/* Sticky TOC */}
        <aside className="hidden lg:block">
          <div className="sticky top-8">
            <p className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-3">
              On this page
            </p>
            <ul className="space-y-1.5 border-l border-gray-200 max-h-[calc(100vh-4rem)] overflow-y-auto">
              <li>
                <a
                  href="#purpose"
                  className="block pl-3 -ml-px border-l border-transparent hover:border-violet-500 text-sm text-gray-600 hover:text-violet-700 py-1 transition-colors">
                  
                  1. Purpose
                </a>
              </li>
              {parts.map((part) =>
              <Fragment key={part.id}>
                  <li className="pt-2">
                    <a
                    href={`#${part.id}`}
                    className="block pl-3 -ml-px border-l border-transparent text-xs font-bold text-violet-700 uppercase tracking-wider py-1">
                    
                      {part.label} — {part.title}
                    </a>
                  </li>
                  {part.sections.map((section) =>
                <li key={section.id}>
                      <a
                    href={`#${section.id}`}
                    className="block pl-3 -ml-px border-l border-transparent hover:border-violet-500 text-sm text-gray-600 hover:text-violet-700 py-1 transition-colors">
                    
                        {section.heading}
                      </a>
                    </li>
                )}
                </Fragment>
              )}
            </ul>
          </div>
        </aside>
      </div>
    </AppLayout>);

}